graphhopper:
  import.osm.ignored_highways: ''
  datareader.file: poland-latest.osm.pbf
  

  profiles:
    - name: all_tracks
      turn_costs:
        vehicle_types: [train, tram, light_rail, subway]
        u_turn_costs: 180
      custom_model_files: [all_tracks.json]

  custom_models.directory: custom_models

  profiles_ch:
    - profile: all_tracks

  graph.encoded_values: gauge,voltage,electrified,frequency,road_environment,max_speed,rail_access,rail_average_speed,railway_class,railway_service,preferred_direction

  prepare.min_network_size: 200
  prepare.subnetworks.threads: 1

  routing.timeout_ms: 20000
  routing.non_ch.max_waypoint_distance: 100000

  graph.dataaccess.default_type: RAM_STORE
  graph.location: graph-cache/graph-ready
  datareader.preferred_language: pl


server:
  application_connectors:
  - type: http
    port: 9000
    bind_host: 0.0.0.0
    max_request_header_size: 50k

  request_log:
      appenders: []

  admin_connectors:
  - type: http
    port: 9001
    bind_host: localhost

logging:
  level: INFO

  appenders:
    - type: console
      time_zone: UTC
      log_format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

    - type: file
      current_log_filename: logs/graphhopper.log
      archive: false
      log_format: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

  loggers:
    "com.graphhopper.osm_warnings":
      level: DEBUG
      additive: false
      appenders:
        - type: console
          log_format: "[%level] %msg%n"
        - type: file
          current_log_filename: logs/graphhopper.log
          archive: false
          log_format: "[%level] %msg%n"
